title: Prestamigo Blog  
description: Guías sobre préstamos y financiamiento en Estados Unidos.  
theme: minima  # Default theme (change later if needed)  
plugins:  
  - jekyll-seo-tag  # For SEO optimization  
