name: Update Mortgage Rates
on:
  schedule:
    # Runs at 11:30 AM UTC every Thursday (when Freddie Mac releases rates)
    - cron: '30 11 * * 4'
  workflow_dispatch: # Allows manual triggering

jobs:
  update-rates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Fetch Freddie Mac Rates
        id: fetch-rates
        uses: satackey/action-freddie-mac-rates@v1
        with:
          primary_mortgage_market_survey: true
          
      - name: Update Rates File
        run: |
          # Parse the fetched rates
          FHA_RATE=$(echo '${{ steps.fetch-rates.outputs.rates }}' | jq -r '.PMMS.rate30YearFixed')
          CONV_RATE=$(echo '${{ steps.fetch-rates.outputs.rates }}' | jq -r '.PMMS.rate30YearFixed')
          ITIN_RATE=$(echo "scale=2; $FHA_RATE + 1.0" | bc)
          
          # Create updated JSON
          echo '{
            "last_updated": "'$(date +%Y-%m-%d)'",
            "rates": {
              "FHA": '$FHA_RATE',
              "CONV": '$CONV_RATE',
              "ITIN": '$ITIN_RATE'
            }
          }' > rates.json
          
      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add rates.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update mortgage rates [skip ci]"
          git push
